# Generated by Django 5.2.5 on 2025-08-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('E', 'Entregue'), ('A', 'Em analise'), ('C', 'Concluído')])),
                ('data', models.DateField()),
                ('anexo', models.CharField(max_length=40)),
                ('tipo_ocorrencia', models.CharField(choices=[('D', 'Denúncia'), ('S', 'Sugestão'), ('R', 'Reclamação')])),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=1000)),
                ('tipo_postagem', models.CharField(choices=[('A', 'Aviso'), ('E', 'Enquete')], max_length=1)),
                ('data', models.DateField()),
                ('imagem', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem', to='core.postagem')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
    ]
