# Generated by Django 5.2.5 on 2025-08-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
