# Generated by Django 5.2.5 on 2025-08-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('E', 'Entregue'), ('A', 'Em analise'), ('C', 'Concluído')])),
                ('data', models.DateField()),
                ('anexo', models.CharField(max_length=40)),
                ('tipo_ocorrencia', models.CharField(choices=[('D', 'Denúncia'), ('S', 'Sugestão'), ('R', 'Reclamação')])),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
            ],
        ),
    ]
