# Generated by Django 5.2.3 on 2025-08-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ocorrencia_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=1000)),
                ('tipo_postagem', models.CharField(choices=[('A', 'Aviso'), ('E', 'Enquete')], max_length=1)),
                ('data', models.DateField()),
                ('imagem', models.CharField(blank=True, max_length=120, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='core.setor')),
            ],
        ),
    ]
