# Generated by Django 5.2.3 on 2025-08-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem', to='core.postagem')),
            ],
        ),
    ]
