# Generated by Django 5.2.5 on 2025-09-02 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ocorrencia_usuario_postagem_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='setor',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_recebidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
