# Generated by Django 5.2.5 on 2025-09-04 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ocorrencia_setor'),
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='anexo',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='anonima',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='setor',
            field=models.ForeignKey(limit_choices_to={'tipo': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('E', 'Entregue'), ('A', 'Em analise'), ('CR', 'Concluído (Resolvido)'), ('CN', 'Concluído (Não resolvido)')]),
        ),
    ]
