# Generated by Django 5.2.5 on 2025-09-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ocorrencia_anexo_ocorrencia_anonima_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entregue'), (2, 'Em analise'), (3, 'Concluído'), (4, 'Concluído não resolvido')], default=1),
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='core.ocorrencia')),
            ],
        ),
    ]
