# Generated by Django 5.2.6 on 2025-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ocorrencia_status_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='tipo_ocorrencia',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Denúncia'), (2, 'Sugestão'), (3, 'Queixa')], default=1),
            preserve_default=False,
        ),
    ]
