# Generated by Django 5.2.5 on 2025-09-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ocorrencia_tipo_ocorrencia_ocorrencia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='texto',
            field=models.TextField(),
        ),
    ]
