# Generated by Django 5.2.6 on 2025-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ocorrencia_tipo_ocorrencia_ocorrencia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='tipo_postagem',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.CharField(max_length=15),
        ),
    ]
