# Generated by Django 5.2.5 on 2025-09-17 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ocorrencia_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
            preserve_default=False,
        ),
    ]
