# Generated by Django 5.2.6 on 2025-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_postagem_tipo_postagem_alter_postagem_data'),
        ('core', '0009_ocorrencia_categoria'),
    ]

    operations = [
    ]
