# Generated by Django 5.2.5 on 2025-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilaluno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='perfilaluno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilsetor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('SETOR', 'setor'), ('ALUNO', 'aluno')], default='ALUNO'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.DeleteModel(
            name='PerfilAluno',
        ),
        migrations.DeleteModel(
            name='PerfilSetor',
        ),
    ]
