# Generated by Django 5.2.5 on 2025-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_setor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Aluno'), (2, 'Setor')], default=1, verbose_name='Tipo de usuário'),
        ),
    ]
