# Generated by Django 5.2.5 on 2025-08-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('usuario', '0003_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='core.curso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
