# Generated by Django 5.2.5 on 2025-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_username_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
